version: 0.1

env:
  parameter-store:
    PI_DNS: /codebuild/piDns

phases:
  install:
    commands:
      - gem install jekyll bundler jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync . s3://roarcoder.dev
      - echo "******** Get ssh key from S3 ********"
      - aws s3 cp s3://ssh-keys-zain/encrypted_id_rsa $HOME/encrypted_id_rsa
      - aws kms decrypt --ciphertext-blob fileb://$HOME/encrypted_id_rsa --output text --query Plaintext | base64 --decode > $HOME/decrypted_id_rsa
      - chmod 400 $HOME/decrypted_id_rsa
      - echo "******** Upload to Raspberry Pi ********"
      - scp -r -oStrictHostKeyChecking=no -i $HOME/decrypted_id_rsa ./* pi@$PI_DNS:/var/www/html/
      - rm $HOME/decrypted_id_rsa
      - rm $HOME/encrypted_id_rsa
  post_build:
   commands:
      - aws cloudfront create-invalidation --distribution-id E7P8BMIOWTPBG --paths '/*'