version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll bundler jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync . s3://roarcoder.dev
  post_build:
   commands:
      - aws cloudfront create-invalidation --distribution-id E7P8BMIOWTPBG --paths '/*'